services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
    command: npm run dev
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  etl-worker:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
    command: npm run etl:dev
    depends_on:
      - backend
      - redis

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev